name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o cli-linux

      - name: Build for Mac
        run: GOOS=darwin GOARCH=amd64 go build -o cli-mac

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o cli-windows.exe

      - name: Create Release Directory
        run: mkdir release

      - name: Move Linux Executable
        run: mv cli-linux release/

      - name: Move Mac Executable
        run: mv cli-mac release/

      - name: Move Windows Executable
        run: mv cli-windows.exe release/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cli-binaries
          path: release/
